/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GNUbka3J4wI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export default function HomeComp() {
  return (
    <div className="flex flex-col items-center w-full min-h-screen bg-gray-100 p-4">
      <header className="w-full max-w-4xl py-6 text-center">
        <h1 className="text-4xl font-bold">Ultimate Car Steering Wheel Lock</h1>
        <p className="mt-2 text-lg text-gray-700">Secure your vehicle with our top-rated steering wheel lock.</p>
      </header>
      <main className="w-full max-w-4xl bg-white rounded-lg shadow-md p-6">
        <div className="flex flex-col md:flex-row gap-6">
          <div className="w-full md:w-1/2">
            <img
              src="/placeholder.svg"
              alt="Car Steering Wheel Lock"
              className="w-full h-auto rounded-lg"
              width="1152"
              height="768"
              style={{ aspectRatio: "1152/768", objectFit: "cover" }}
            />
          </div>
          <div className="w-full md:w-1/2 flex flex-col justify-between">
            <div>
              <h2 className="text-2xl font-semibold">Features</h2>
              <ul className="mt-4 space-y-2 text-gray-700">
                <li>🔒 High-security lock mechanism</li>
                <li>🔧 Easy to install and remove</li>
                <li>🔨 Made from durable materials</li>
                <li>🚗 Fits most car steering wheels</li>
              </ul>
              <h2 className="mt-6 text-2xl font-semibold">Specifications</h2>
              <ul className="mt-4 space-y-2 text-gray-700">
                <li>Material: Hardened steel</li>
                <li>Weight: 1.5 kg</li>
                <li>Dimensions: 35 cm x 15 cm x 10 cm</li>
                <li>Color: Black</li>
              </ul>
            </div>
            <div className="mt-6">
              <h2 className="text-2xl font-semibold">Price: $49.99</h2>
              <Button className="mt-4 w-full">Buy Now</Button>
            </div>
          </div>
        </div>
      </main>
      <footer className="w-full max-w-4xl py-6 mt-8 text-center text-gray-600">
        &copy; 2023 Car Security Solutions. All rights reserved.
      </footer>
    </div>
  )
}
